### ISSUE TITLE
Support non-dialog usage

### ISSUE THREAD

**Issue by jackrabbit128** [ricemery/FileChooserFx#14]
I have one more thing that I would like to contribute, but it may be out-of-scope for what you intend this library to be:

My actual use case is to embed the file chooser inside a ControlsFx wizard page (minus the buttons at the bottom, but I can arrange through CSS). To enable this usage, I added additional methods to `FileChooserFxImpl` and `DirectoryChooserFxImpl` that essentially duplicate the `show*Dialog` methods to `create*Node` instead. I am pretty new to JavaFX, so it is entirely possible that I am doing weird things here.
The changes are in my [non-dialog-usage](https://github.com/jackrabbit128/FileChooserFx/commits/non-dialog-usage) branch.

Is this something you would be interested in?

**Comment by ricemery** [comment]
Your changes look good to me. This seems like a good use case to support.

A couple of things.
1) I think the last four statemes of showDialog and createNode should probably be moved into a method and shared. It seems like these could easily become out of sync.
<pre> placesView.updatePlaces();
currentDirectory = getInitialDirectory() == null
        ? new File(".")
        : initialDirectory.getValue();

setCurrentView(viewTypeProperty().getValue());
updateWatchDirectory();
</pre>

2) It would be nice if the new functionality was included in either the existing FileChooserDemo or in another demo application. 

Thanks,
Ric

**Comment by jackrabbit128** [comment]
Great!

It will be a couple of days before I can work on this again, but I'll make the changes you suggest.

I was going for minimal changes, but as we are into refactoring now: longer term, I would extract a `FileChooserFxPane` out of `FileChooserFxImpl` so that the latter only deals with the dialog and button stuff. That would also immediately validate that the pane can easily be integrated in any other UI.
